### ISSUE TITLE
Consegue me ajudar?

### ISSUE THREAD

**Issue by FernandoVenuto** [GuilhermeCastelo/PHP_OO#1]
Será que você consegue me ajudar com o código desta aula, tentei fazer diferente e utilizar o "Switch" para mudar o setTrabalhando

    public function mudarTrabalho() {
        $mudar = rand(0, 2);
        switch ($mudar) {
            case 0: // Pedreiro
                $this->setTrabalhando("Pedreiro");
                break;
            case 1: // Limpeza
                echo "Auxiliar de Limpeza";
                break;
            case 2: //Administração
                echo "Administração";
                break;
        }
    }
    
    porém não ta indo... sabe oq pode ser?

**Comment by GuilhermeCastelo** [comment]
Oi, Fernando! Tudo bem?

Então, existem 2 pontos no seu código que podem estar causando erro, fazendo com que você não veja o resultado que espera.

1º Você não definiu um valor para **$this->setTrabalhando()**

**Comment by GuilhermeCastelo** [comment]
Oi, Fernanda! Tudo bem?

Então, existem 2 pontos no seu código que podem estar errados, fazendo com que você não veja o resultado que espera.

1º Você não definiu um valor para **$this->setTrabalhando()** para os casos **1** e **2**.
2º Você tentou utilizar o **print_r(nomedoobejo)**?

Segue um exemplo baseado no seu código:

Arquivo **index.php**:

<?php
    require_once 'Trabalho.php';

    $t1 = new Trabalho;

    $t1->mudarTrabalho();

    print_r($t1);
?>

_____________________________________________

Arquivo **Trabalho.php**:

<?php
    class Trabalho{

    public $trb;

    public function getTrabalhando(){
        return $this->trabalhando;
    }

    public function setTrabalhando($trb){
        $this->trabalhando = $trb;
    }

    public function mudarTrabalho() {
        $mudar = rand(0, 2);

        switch ($mudar) {
            case 0: // Pedreiro
                $this->setTrabalhando("Pedreiro");
                break;
            case 1: // Limpeza
                $this->setTrabalhando("Auxiliar de Limpeza");
                break;
            case 2: //Administração
                $this->setTrabalhando("Administração");
                break;
        }
    }
}
?>

Tente comparar e testar os 2 códigos para notar a diferença no resultado. Espero ter te ajudado! 😉

**Comment by GuilhermeCastelo** [comment]
Oi, Fernando! Tudo bem? 😊

Então, existem 2 pontos no seu código que podem estar errados, fazendo com que você não veja o resultado que espera.

1º Você não definiu um valor para **$this->setTrabalhando()** para os casos **1** e **2**.
2º Você tentou utilizar o **print_r(nomedoobejo)**?

Segue um exemplo baseado no seu código:

Arquivo **index.php**:

<?php
    require_once 'Trabalho.php';

    $t1 = new Trabalho;

    $t1->mudarTrabalho();

    print_r($t1);
?>

_____________________________________________

Arquivo **Trabalho.php**:

<?php
    class Trabalho{

    public $trb;

    public function getTrabalhando(){
        return $this->trabalhando;
    }

    public function setTrabalhando($trb){
        $this->trabalhando = $trb;
    }

    public function mudarTrabalho() {
        $mudar = rand(0, 2);

        switch ($mudar) {
            case 0: // Pedreiro
                $this->setTrabalhando("Pedreiro");
                break;
            case 1: // Limpeza
                $this->setTrabalhando("Auxiliar de Limpeza");
                break;
            case 2: //Administração
                $this->setTrabalhando("Administração");
                break;
        }
    }
}
?>

__________________________________________________

Tente comparar e testar os 2 códigos para notar a diferença no resultado. Espero ter te ajudado! 😉

**Comment by guilhermecastelo** [comment]
Oi, Fernando! Tudo bem? 😊

Então, existem 2 pontos no seu código que podem estar errados, fazendo com que você não veja o resultado que espera.

1º Você não definiu um valor para **$this->setTrabalhando()** para os casos **1** e **2**.
2º Você tentou utilizar o **print_r(nomedoobjeto)**?

Segue um exemplo baseado no seu código:

Arquivo **index.php**:

    require_once 'Trabalho.php';

    $t1 = new Trabalho;

    $t1->mudarTrabalho();

    print_r($t1);

_____________________________________________

Arquivo **Trabalho.php**:

    class Trabalho{

    public $trb;

    public function getTrabalhando(){
        return $this->trabalhando;
    }

    public function setTrabalhando($trb){
        $this->trabalhando = $trb;
    }

    public function mudarTrabalho() {
        $mudar = rand(0, 2);

        switch ($mudar) {
            case 0: // Pedreiro
                $this->setTrabalhando("Pedreiro");
                break;
            case 1: // Limpeza
                $this->setTrabalhando("Auxiliar de Limpeza");
                break;
            case 2: //Administração
                $this->setTrabalhando("Administração");
                break;
        }
    }
__________________________________________________

Tente comparar e testar os 2 códigos para notar a diferença no resultado. Espero ter te ajudado! 😉

**Comment by guilhermecastelo** [comment]
Conseguiu resolver e notar a diferença?

**Comment by FernandoVenuto** [comment]
Consegui sim mano.

O codigo realmente estava errado.
Porém o problema real era que o "print_r( )" estava em cima do metodo, ai não estava mudando.
Valeu pela ajuda.

**Comment by GuilhermeCastelo** [comment]
Ah! Maravilha.
Fico feliz em ter ajudado :)

**Comment by guilhermecastelo** [comment]
Ah! Maravilha.
Fico feliz em ter ajudado :)
